name: qrcode_scanner
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.2
  path_provider:
  hive_flutter: ^1.1.0
  # url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  hive_generator:
  build_runner:

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
